/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "My Site",
  "tagline": "Dinosaurs are cool",
  "favicon": "img/paper.png",
  "url": "https://your-docusaurus-site.example.com",
  "baseUrl": "/",
  "organizationName": "facebook",
  "projectName": "docusaurus",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "plugins": [
    "docusaurus-plugin-sass"
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.js"
        },
        "blog": {
          "showReadingTime": true,
          "feedOptions": {
            "type": [
              "rss",
              "atom"
            ],
            "xslt": true
          },
          "editUrl": "https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/",
          "onInlineTags": "warn",
          "onInlineAuthors": "warn",
          "onUntruncatedBlogPosts": "warn"
        },
        "theme": {
          "customCss": [
            "/home/chopper/resume/src/css/customTheme.scss",
            "/home/chopper/resume/src/css/index.scss",
            "/home/chopper/resume/src/css/showcase.scss",
            "/home/chopper/resume/src/css/versions.scss"
          ]
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/paper.png",
    "navbar": {
      "title": "Homepage",
      "logo": {
        "alt": "My Site Logo",
        "src": "img/paper.png"
      },
      "style": "dark",
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "Resume"
        },
        {
          "href": "https://github.com/g-despot",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Portfolio",
          "items": [
            {
              "label": "Intro",
              "to": "/docs/intro"
            },
            {
              "label": "Resume",
              "to": "/docs/resume/ericsson"
            },
            {
              "label": "Experience & Skills",
              "to": "/docs/experience/software-development"
            }
          ]
        },
        {
          "title": "Social channels",
          "items": [
            {
              "label": "Medium",
              "href": "https://gdespot.medium.com/"
            },
            {
              "label": "Twitter",
              "href": "https://x.com/ivan_g_despot"
            },
            {
              "label": "Stack Overflow",
              "href": "https://stackoverflow.com/users/14674424/ivan-despot"
            }
          ]
        },
        {
          "title": "Other channels",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/g-despot"
            },
            {
              "label": "LinkedIn",
              "href": "https://www.linkedin.com/in/ivan-g-despot/"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2024 Ivan Despot"
    },
    "prism": {
      "defaultLanguage": "jsx",
      "theme": {
        "plain": {
          "color": "#FFFFFF",
          "backgroundColor": "#282C34"
        },
        "styles": [
          {
            "types": [
              "property"
            ],
            "style": {
              "color": "#2aa198"
            }
          },
          {
            "types": [
              "attr-name",
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#93a1a1"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "style": {
              "color": "#657b83"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "selector",
              "char",
              "builtin",
              "url"
            ],
            "style": {
              "color": "#2aa198"
            }
          },
          {
            "types": [
              "entity"
            ],
            "style": {
              "color": "#2aa198"
            }
          },
          {
            "types": [
              "atrule",
              "inserted"
            ],
            "style": {
              "color": "#859900"
            }
          },
          {
            "types": [
              "important",
              "variable",
              "deleted"
            ],
            "style": {
              "color": "#cb4b16"
            }
          },
          {
            "types": [
              "important",
              "bold"
            ],
            "style": {
              "fontWeight": "bold"
            }
          },
          {
            "types": [
              "italic"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "entity"
            ],
            "style": {
              "cursor": "help"
            }
          },
          {
            "types": [
              "attr-name",
              "keyword"
            ],
            "style": {
              "color": "#c5a5c5"
            }
          },
          {
            "types": [
              "string",
              "regex",
              "attr-value"
            ],
            "style": {
              "color": "#8dc891"
            }
          },
          {
            "types": [
              "number",
              "constant",
              "symbol"
            ],
            "style": {
              "color": "#5a9bcf"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "#ff8b50"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "#fac863"
            }
          },
          {
            "types": [
              "function"
            ],
            "style": {
              "color": "#79b6f2"
            }
          },
          {
            "types": [
              "operator",
              "tag"
            ],
            "style": {
              "color": "#fc929e"
            }
          }
        ]
      },
      "additionalLanguages": [
        "diff",
        "bash",
        "json",
        "java",
        "kotlin",
        "objectivec",
        "swift",
        "groovy",
        "ruby",
        "flow"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
